services:
  animalpicturesapi:
    image: animalpicturesapi
    build:
      context: ./AnimalPicturesApi
      dockerfile: ./Dockerfile
    ports:
      - 7258:8080
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=animals
      - MYSQL_ROOT_PASSWORD=test123
    ports:
      - '3306:3306'
